spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.104/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: true
    #default-property-inclusion: non_null
    #date-format: yyyy-MM-dd HH:mm:ss
    #time-zone: GMT+8
server:
  servlet:
    context-path: /sell
logging:
  pattern:
    console: "%d - %msg%n"
  #path: /var/log/testlog
  #file: /var/log/
  #level: debug